version: "3.9"


networks:
  jmfood-network:
    driver: bridge
    
services:
  jmfood-mysql:
    image: mysql:8.0
    environment:
       MYSQL_ROOT_PASSWORD: "marcos10"
    ports:
      - "3306:3306"
    networks:
      - jmfood-network 
      
  jmfood-redis:
    image: redis:6.2.1-alpine
    networks:
      - jmfood-network

    

  jmfood-api:
    image: jmfood-api
    command: ["/wait-for-it.sh", "jmfood-mysql:3306", "-t", "500", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: jmfood-mysql
    networks:
      - jmfood-network
    depends_on:
     - jmfood-mysql
       

  jmfood-proxy:
    build: ./nginx
    image: jmfood-proxy
    ports:
      - "80:80"
    networks:
      - jmfood-network
    depends_on:
      - jmfood-api