version: "3.9"

networks:
  jmfood-network:
    driver: bridge

services:
  jmfood-mysql:
    image: mysql:8.0
    environment:
       MYSQL_ROOT_PASSWORD: "marcos10"
    ports:
      - "3306:3306"
    networks:
      - jmfood-network

  jmfood-api:
    image: jmfood-api
    command: ["/wait-for-it.sh", "jmfood-mysql:3306", "-t", "30", "--", "java", "-jar", "jmfood.jar"]
    environment:
      DB_HOST: jmfood-mysql
    ports:
      - "8080:8080"
    networks:
      - jmfood-network
    depends_on:
      - jmfood-mysql
      