version: "3.9"

networks:
  jmfood-network:
    driver: bridge
    
services:
  jmfood-mysql:
    image: mysql:8.0
    environment:
       MYSQL_ROOT_PASSWORD: "marcos10"
    ports:
      - "3306:3306"
    networks:
      - jmfood-network 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s  
      timeout: 20s
      retries: 10

  jmfood-api:
    image: jmfood-api
    command: ["java", "-jar", "jmfood.jar"]
    environment:
      DB_HOST: jmfood-mysql
    networks:
      - jmfood-network
    depends_on:
      jmfood-mysql:
       condition: service_healthy
       
  jmfood-proxy:
   build: ./nginx
   image: jmfood-proxy
   ports:
    - "80:80"
   networks:  
       - jmfood-network
   depends_on:
    - jmfood-api